### ISSUE TITLE
如何在自己的输入法中加上“以词定字”功能呢

### ISSUE THREAD

**Issue by naosense** [Reniastyc/rime-double-terra#1]
目前我做的：
1. 将`lua`文件夹放在了用户文件夹
2. 将`* ?`放在了我的词典文件中
3. 将以下三行加到了我的double_pinyin.schema.yaml中
```yaml
  alphabet: 'zyxwvutsrqponmlkjihgfedcba-;/<,>.\?'
  initials: 'zyxwvutsrqponmlkjihgfedcba'
  finals: '-;/<,>.\?'
```
现在输入suoshi，再输入?，显示如下
<img width="92" alt="image" src="https://github.com/Reniastyc/rime-double-terra/assets/2225426/7de31ec3-90a0-4979-9434-75114774aa0b">
